Repository Ndisyamwende/Beautyshop-backend, pull requests merged in 2024-05, with the labels that each got.

#8 setting up the working space
  app/models.py
  app/seed.py
Labels: enhancement

#17 Feature/homepage
  README.md
  app/app.py
Labels: bug

#18 Feature/productmodel
  README.md
  app/app.py
Labels: enhancement

#19 Feature/homepage
  README.md
  app/models.py
  app/seed.py
Labels: bug

#22 Feature/authentication
  app/app.py
  app/config.py
  app/models.py
  app/seed.py
Labels: enhancement

#23 Done
  app/checkout.py
Labels: enhancement

#24 Navbar
  app/Navbar.py
Labels: enhancement

#25 Updated
  app/app.py
Labels: enhancement

#26 Feature/homepage
  app/Navbar.py
  app/checkout.py
  app/config.py
Labels: bug

#27 Feature/homepage
  app/app.py
  app/config.py
  app/models.py
  app/seed.py
Labels: duplicate

#28 Feature/contact model
  app/app.py
  app/models.py
  app/seed.py
Labels: enhancement

#32 Feature/productmodel
  app/app.py
  app/config.py
  app/models.py
Labels: enhancement

#33 Feature/homepage
  app/models.py
Labels: enhancement

#34 Feature/contact model
  app/app.py
  app/models.py
  app/seed.py
Labels: enhancement

#35 category model added
  app/models.py
Labels: enhancement

#36 Feature/productmodel
  app/app.py
  app/models.py
Labels: enhancement

#37 Feature/productmodel
  app/app.py
  app/migrations/README
  app/migrations/alembic.ini
  app/migrations/env.py
  app/migrations/script.py.mako
  app/models.py
  app/seed.py
Labels: enhancement

#39 Feature/authentication
  app/app.py
  app/migrations/versions/6eba5c37edd1_inial_migration.py
  app/models.py
  app/seed.py
Labels: bug

#40 Feature/homepage
  app/migrations/versions/bc254e7cc3b8_initial_migration.py
  app/seed.py
Labels: bug

#43 Feature/homepage
  .flaskenv
  app/app.py
  app/models.py
  app/seed.py
  requirements.txt
  run.py
Labels: enhancement
